/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutConstellationRouteImport } from './routes/_layout/constellation'
import { Route as LayoutDigestIndexRouteImport } from './routes/_layout/digest/index'
import { Route as LayoutBlogIndexRouteImport } from './routes/_layout/blog/index'
import { Route as LayoutDigestSlugRouteImport } from './routes/_layout/digest/$slug'
import { Route as LayoutBlogSlugRouteImport } from './routes/_layout/blog/$slug'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutConstellationRoute = LayoutConstellationRouteImport.update({
  id: '/constellation',
  path: '/constellation',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDigestIndexRoute = LayoutDigestIndexRouteImport.update({
  id: '/digest/',
  path: '/digest/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBlogIndexRoute = LayoutBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDigestSlugRoute = LayoutDigestSlugRouteImport.update({
  id: '/digest/$slug',
  path: '/digest/$slug',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBlogSlugRoute = LayoutBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/constellation': typeof LayoutConstellationRoute
  '/blog/$slug': typeof LayoutBlogSlugRoute
  '/digest/$slug': typeof LayoutDigestSlugRoute
  '/blog/': typeof LayoutBlogIndexRoute
  '/digest/': typeof LayoutDigestIndexRoute
}
export interface FileRoutesByTo {
  '/constellation': typeof LayoutConstellationRoute
  '/': typeof LayoutIndexRoute
  '/blog/$slug': typeof LayoutBlogSlugRoute
  '/digest/$slug': typeof LayoutDigestSlugRoute
  '/blog': typeof LayoutBlogIndexRoute
  '/digest': typeof LayoutDigestIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/constellation': typeof LayoutConstellationRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/blog/$slug': typeof LayoutBlogSlugRoute
  '/_layout/digest/$slug': typeof LayoutDigestSlugRoute
  '/_layout/blog/': typeof LayoutBlogIndexRoute
  '/_layout/digest/': typeof LayoutDigestIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/constellation'
    | '/blog/$slug'
    | '/digest/$slug'
    | '/blog/'
    | '/digest/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/constellation'
    | '/'
    | '/blog/$slug'
    | '/digest/$slug'
    | '/blog'
    | '/digest'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/constellation'
    | '/_layout/'
    | '/_layout/blog/$slug'
    | '/_layout/digest/$slug'
    | '/_layout/blog/'
    | '/_layout/digest/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/constellation': {
      id: '/_layout/constellation'
      path: '/constellation'
      fullPath: '/constellation'
      preLoaderRoute: typeof LayoutConstellationRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/digest/': {
      id: '/_layout/digest/'
      path: '/digest'
      fullPath: '/digest/'
      preLoaderRoute: typeof LayoutDigestIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/blog/': {
      id: '/_layout/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof LayoutBlogIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/digest/$slug': {
      id: '/_layout/digest/$slug'
      path: '/digest/$slug'
      fullPath: '/digest/$slug'
      preLoaderRoute: typeof LayoutDigestSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/blog/$slug': {
      id: '/_layout/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof LayoutBlogSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutConstellationRoute: typeof LayoutConstellationRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutBlogSlugRoute: typeof LayoutBlogSlugRoute
  LayoutDigestSlugRoute: typeof LayoutDigestSlugRoute
  LayoutBlogIndexRoute: typeof LayoutBlogIndexRoute
  LayoutDigestIndexRoute: typeof LayoutDigestIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutConstellationRoute: LayoutConstellationRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutBlogSlugRoute: LayoutBlogSlugRoute,
  LayoutDigestSlugRoute: LayoutDigestSlugRoute,
  LayoutBlogIndexRoute: LayoutBlogIndexRoute,
  LayoutDigestIndexRoute: LayoutDigestIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
